### ISSUE TITLE
Project level tours not loading

### ISSUE THREAD

**Issue by pwonson** [rundeck-plugins/http-tours#1]
When the configuration is set at the project level and not the framework properties. The tour files are not loaded.

No error messages appear in the service.log.

Config example:

project.plugin.TourLoader.httptours.tourEndpoint=https\://guided-tours.s3-us-west-2.amazonaws.com/basic-tour

Tour files in an S3 bucket that has public read access:
https://guided-tours.s3-us-west-2.amazonaws.com/basic-tour/tour-manifest.json
https://guided-tours.s3-us-west-2.amazonaws.com/basic-tour/tours/getting-started.json

(Note that the tour manifest points to a few more files than actually exist because I am writing new tours for the demo and using these as a starting point - so the missing three other tour files is expected behavior for now.)

**Comment by sjrd218** [comment]
Fixed in Rundeck 3.1.1.
https://github.com/rundeck/rundeck/pull/5192
